// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raft.proto

package idl

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RaftProposal struct {
	Cmds                 [][]byte `protobuf:"bytes,1,rep,name=cmds,proto3" json:"cmds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftProposal) Reset()         { *m = RaftProposal{} }
func (m *RaftProposal) String() string { return proto.CompactTextString(m) }
func (*RaftProposal) ProtoMessage()    {}
func (*RaftProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{0}
}

func (m *RaftProposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftProposal.Unmarshal(m, b)
}
func (m *RaftProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftProposal.Marshal(b, m, deterministic)
}
func (m *RaftProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftProposal.Merge(m, src)
}
func (m *RaftProposal) XXX_Size() int {
	return xxx_messageInfo_RaftProposal.Size(m)
}
func (m *RaftProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftProposal.DiscardUnknown(m)
}

var xxx_messageInfo_RaftProposal proto.InternalMessageInfo

func (m *RaftProposal) GetCmds() [][]byte {
	if m != nil {
		return m.Cmds
	}
	return nil
}

func init() {
	proto.RegisterType((*RaftProposal)(nil), "idl.RaftProposal")
}

func init() {
	proto.RegisterFile("raft.proto", fileDescriptor_b042552c306ae59b)
}

var fileDescriptor_b042552c306ae59b = []byte{
	// 79 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x4a, 0x4c, 0x2b,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x4c, 0xc9, 0x51, 0x52, 0xe2, 0xe2, 0x09,
	0x4a, 0x4c, 0x2b, 0x09, 0x28, 0xca, 0x2f, 0xc8, 0x2f, 0x4e, 0xcc, 0x11, 0x12, 0xe2, 0x62, 0x49,
	0xce, 0x4d, 0x29, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x09, 0x02, 0xb3, 0x93, 0xd8, 0xc0, 0xea,
	0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x9c, 0x68, 0x8e, 0x3d, 0x00, 0x00, 0x00,
}
